# FOSUserBundle

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /rejoindre

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /parametres

fos_user_profile_show:
    path:   /me
    defaults:  { _controller: LadbCoreBundle:Core/User:showMe }

# Imagine Bundle

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

# Webpush Bundle

bentools_webpush:
    resource: '@WebPushBundle/Resources/config/routing.xml'
    prefix: /webpush

# Ladb Bundles

ladb_core:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\DefaultController"
    type:     annotation

ladb_core_api:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\ApiController"
    type:     annotation

ladb_core_wonder_creation:
    resource: "Ladb\\CoreBundle\\Controller\\Wonder\\CreationController"
    type:     annotation

ladb_core_wonder_workshop:
    resource: "Ladb\\CoreBundle\\Controller\\Wonder\\WorkshopController"
    type:     annotation

ladb_core_wonder_plan:
    resource: "Ladb\\CoreBundle\\Controller\\Wonder\\PlanController"
    type:     annotation

ladb_core_howto:
    resource: "Ladb\\CoreBundle\\Controller\\Howto\\HowtoController"
    type:     annotation

ladb_core_howto_article:
    resource: "Ladb\\CoreBundle\\Controller\\Howto\\ArticleController"
    type:     annotation

ladb_core_find:
    resource: "Ladb\\CoreBundle\\Controller\\Find\\FindController"
    type:     annotation

ladb_core_event:
    resource: "Ladb\\CoreBundle\\Controller\\Event\\EventController"
    type:     annotation

ladb_core_blog:
    resource: "Ladb\\CoreBundle\\Controller\\Blog\\PostController"
    type:     annotation

ladb_core_about:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\AboutController"
    type:     annotation

ladb_core_faq_question:
    resource: "Ladb\\CoreBundle\\Controller\\Faq\\QuestionController"
    type:     annotation

ladb_core_message:
    resource: "Ladb\\CoreBundle\\Controller\\Message\\MessageController"
    type:     annotation

ladb_core_thread:
    resource: "Ladb\\CoreBundle\\Controller\\Message\\ThreadController"
    type:     annotation

ladb_core_notification:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\NotificationController"
    type:     annotation

ladb_core_search:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\SearchController"
    type:     annotation

ladb_core_comment:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\CommentController"
    type:     annotation

ladb_core_follower:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\FollowerController"
    type:     annotation

ladb_core_like:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\LikeController"
    type:     annotation

ladb_core_watch:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\WatchController"
    type:     annotation

ladb_core_vote:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\VoteController"
    type:     annotation

ladb_core_join:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\JoinController"
    type:     annotation

ladb_core_report:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\ReportController"
    type:     annotation

ladb_core_tag:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\TagController"
    type:     annotation

ladb_core_picture:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\PictureController"
    type:     annotation

ladb_core_resource:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\ResourceController"
    type:     annotation

ladb_core_review:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\ReviewController"
    type:     annotation

ladb_core_tip:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\TipController"
    type:     annotation

ladb_core_wood:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\WoodController"
    type:     annotation

ladb_core_provider:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\ProviderController"
    type:     annotation

ladb_core_school:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\SchoolController"
    type:     annotation

ladb_core_school_testimonial:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\School\\TestimonialController"
    type:     annotation

ladb_core_book:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\BookController"
    type:     annotation

ladb_core_software:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\SoftwareController"
    type:     annotation

ladb_core_knowledge:
    resource: "Ladb\\CoreBundle\\Controller\\Knowledge\\KnowledgeController"
    type:     annotation

ladb_core_referer:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\RefererController"
    type:     annotation

ladb_core_funding:
    resource: "Ladb\\CoreBundle\\Controller\\Funding\\FundingController"
    type:     annotation

ladb_core_promotion:
    resource: "Ladb\\CoreBundle\\Controller\\Promotion\\GraphicController"
    type:     annotation

ladb_core_youtook:
    resource: "Ladb\\CoreBundle\\Controller\\Extra\\YoutookController"
    type:     annotation

ladb_core_qa_question:
    resource: "Ladb\\CoreBundle\\Controller\\Qa\\QuestionController"
    type:     annotation

ladb_core_qa_answer:
    resource: "Ladb\\CoreBundle\\Controller\\Qa\\AnswerController"
    type:     annotation

ladb_core_workflow:
    resource: "Ladb\\CoreBundle\\Controller\\Workflow\\WorkflowController"
    type:     annotation

ladb_core_workflow_task:
    resource: "Ladb\\CoreBundle\\Controller\\Workflow\\TaskController"
    type:     annotation

ladb_core_workflow_part:
    resource: "Ladb\\CoreBundle\\Controller\\Workflow\\PartController"
    type:     annotation

ladb_core_workflow_label:
    resource: "Ladb\\CoreBundle\\Controller\\Workflow\\LabelController"
    type:     annotation

ladb_core_collection:
    resource: "Ladb\\CoreBundle\\Controller\\Collection\\CollectionController"
    type:     annotation

ladb_core_collection_entry:
    resource: "Ladb\\CoreBundle\\Controller\\Collection\\EntryController"
    type:     annotation

ladb_core_offer:
    resource: "Ladb\\CoreBundle\\Controller\\Offer\\OfferController"
    type:     annotation

ladb_core_spotlight:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\SpotlightController"
    type:     annotation

ladb_core_user:
    resource: "Ladb\\CoreBundle\\Controller\\Core\\UserController"
    type:     annotation


